### ISSUE TITLE
Scrollbars problem

### ISSUE THREAD

**Issue by chrilith** [scottcarver/prettify-theme-monokai#1]
Hi,

I'm using your great theme in my JSDoc theme you can see in action here:
http://www.gamalto.com/documentation/index.html

The only problem I had is the scrollbars always appearing because of the style you added.

```css
pre.prettyprint { overflow: scroll; }
```

I think Prettify automatically handles overflows and you should not add this css property.

Thanks!
Chris
